apiVersion: v2
description: Divorce - Respondent Frontend
name: div-rfe
version: 2.0.11
dependencies:
  - name: nodejs
    version: 2.4.3
    repository: '@hmctspublic'
  - name: redis
    version: 10.6.18
    repository: "https://charts.bitnami.com/bitnami"
    tags:
      - pr
  - name: idam-pr
    version: 2.2.6
    repository: '@hmctspublic'
    tags:
      - idam-pr
