dependencies:
  - name: nodejs
    version: 2.0.0
    repository: '@hmctspublic'
  - name: redis
    version: 10.5.7
    repository: '@stable'
    tags:
      - pr
  - name: idam-pr
    version: ~2.2.6
    repository: '@hmctspublic'
    tags:
      - idam-pr
