nodejs:
    applicationPort: 3000
    aadIdentityName: divorce
    image: "hmctspublic.azurecr.io/div/rfe:latest"
    ingressHost: "div-rfe-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal" # override in public facing environments
    memoryLimits: '512Mi'
    memoryRequests: '512Mi'
    cpuLimits: '1000m'
    cpuRequests: '200m'
    autoscaling:
      enabled: true
      maxReplicas: 4
      targetCPUUtilizationPercentage: 80 # Default is 80% target CPU utilization
    environment:
        GOOGLE_ANALYTICS_ID: ""
        GOOGLE_ANALYTICS_TRACKING_URL: "http://www.google-analytics.com/collect"
        NODE_ENV: "production"
        HPKP_MAX_AGE: "86400"
        HPKP_SHAS: "Naw+prhcXSIkbtYJ0t7vAD+Fc92DWL9UZevVfWBvids=,klO23nT2ehFDXCfx3eHTDRESMz3asj1muO+4aIdjiuY=,grX4Ta9HpZx6tSHkmCrvpApTQGo67CYDnvprLg5yRME="
        RATE_LIMITER_ENABLED: "false"
        RATE_LIMITER_TOTAL: "3600"
        RATE_LIMITER_EXPIRE: "3600000"

        POST_CODE_URL: "https://api.os.uk/search/places/v1"

        REFORM_ENVIRONMENT: "{{ .Values.global.environment }}"
        IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
        IDAM_LOGIN_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login"
        COS_BASE_URL: "http://div-cos-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        FEES_AND_PAYMENTS_URL: "http://div-fps-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        DECREE_NISI_FRONTEND_URL: "https://div-dn-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        DECREE_ABSOLUTE_FRONTEND_URL: "https://div-da-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        CASE_MAINTENANCE_BASE_URL: "http://div-cms-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        EVIDENCE_MANAGEMENT_CLIENT_API_URL: "http://div-emca-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        EVIDENCE_MANAGEMENT_CLIENT_API_DOWNLOAD_ENDPOINT: "/emclientapi/version/1/download"
        ANTENNA_WEBCHAT_URL: "webchat.ctsc.hmcts.net"
        ANTENNA_WEBCHAT_SERVICE: "Divorce"
        ANTENNA_WEBCHAT_VERSION: "1"

        ANTENNA_WEBCHAT_AVAILABILITY_DEBUG: "false"
        FEATURE_WEBCHAT_AVAILABILITY_TOGGLE: "false"

        COURT_PHONENUMBER_EN: "0300 303 0642"
        COURT_OPENINGHOURS_EN: 'Monday to Friday, 8am to 6pm'

        FEATURE_DYNATRACE: "false"

    keyVaults:
        div:
            secrets:
                - session-secret
                - redis-secret
                - idam-secret
                - os-places-token
                - redis-connection-string
                - AppInsightsInstrumentationKey
                - launchdarkly-key
                - pcq-token-key

redis:
    cluster:
        enabled: false
        slaveCount: 0
    usePassword: false
    master:
        persistence:
            enabled: false

tags:
  idam-pr: false
  pr: false
