nodejs:
    applicationPort: 3000
    aadIdentityName: divorce
    image: "hmctspublic.azurecr.io/div/rfe:latest"
    ingressHost: "div-rfe-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal" # override in public facing environments
    environment:
        GOOGLE_ANALYTICS_ID: ""
        GOOGLE_ANALYTICS_TRACKING_URL: "http://www.google-analytics.com/collect"
        NODE_ENV: "production"
        HPKP_MAX_AGE: "86400"
        HPKP_SHAS: "Naw+prhcXSIkbtYJ0t7vAD+Fc92DWL9UZevVfWBvids=,klO23nT2ehFDXCfx3eHTDRESMz3asj1muO+4aIdjiuY=,grX4Ta9HpZx6tSHkmCrvpApTQGo67CYDnvprLg5yRME="
        RATE_LIMITER_ENABLED: "false"
        RATE_LIMITER_TOTAL: "3600"
        RATE_LIMITER_EXPIRE: "3600000"

        WEBCHAT_CHAT_ID: 3833071605d5d4518036a09.30917386
        WEBCHAT_TENANT: aG1jdHNzdGFnaW5nMDE
        WEBCHAT_BUTTON_NO_AGENTS: 7732814745cac6f4603c4d1.53357933
        WEBCHAT_BUTTON_AGENTS_BUSY: 2042157415cc19c95669039.65793052
        WEBCHAT_BUTTON_SERVICE_CLOSED: 20199488815cc1a89e0861d5.73103009
        POST_CODE_URL: "https://api.ordnancesurvey.co.uk/places/v1"

        REFORM_ENVIRONMENT: "{{ .Values.global.environment }}"
        IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
        IDAM_LOGIN_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login"
        COS_BASE_URL: "http://div-cos-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        FEES_AND_PAYMENTS_URL: "http://div-fps-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        DECREE_NISI_FRONTEND_URL: "https://div-dn-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        DECREE_ABSOLUTE_FRONTEND_URL: "https://div-da-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        CASE_MAINTENANCE_BASE_URL: "http://div-cms-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        EVIDENCE_MANAGEMENT_CLIENT_API_URL: "http://div-emca-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        EVIDENCE_MANAGEMENT_CLIENT_API_DOWNLOAD_ENDPOINT: "/emclientapi/version/1/download"

    keyVaults:
        div:
            secrets:
                - session-secret
                - redis-secret
                - idam-secret
                - os-places-token
                - rfe-redis-connection-string
                - AppInsightsInstrumentationKey

redis:
    cluster:
        enabled: false
        slaveCount: 0
    usePassword: false
    master:
        persistence:
            enabled: false

tags:
  idam-pr: false
  pr: false
